### ISSUE TITLE
Undefined offset: 0, when checkize(100)

### ISSUE THREAD

**Issue by cmnstmntmn** [gburtini/Humanize-PHP#1]

**Comment by gburtini** [comment]
This fixes it: b4e1f1c348f88e9630e440fbd7bb9f6d19b46307, b06a749ce46d4c9339238ac528379cdd78939db7

But that code is such a mess I am extremely not proud of it. There's also no tests, so it's conceivable I broke something else. I don't have much time to clean up my open source code these days, unfortunately.
